# Generated by Django 6.0.5 on 2026-06-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stripe_price_id_product_stripe_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(max_length=100),
        ),
    ]
